server:
  port: 8070
spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.59.129:8848
      config:
        server-addr: 192.168.59.129:8848
        file-extension: yaml
        shared-adtaids: ces_datasouce.yml