server:
  port: 8070
spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 120.78.206.184:8848
      config:
        server-addr: 120.78.206.184:8848
        file-extension: yaml
        shared-adtaids: ces_datasouce.yml