name: Java CI     #Actions名称

#Action触发条件
on:
  push:
    branches:
      - action

jobs:
  build:
    runs-on: ubuntu-latest    #运行环境
  steps:
    - uses: actions/checkout@v1    #获得你该仓库的v1分支
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2  #使用官方脚本创建java环境
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
